"""init_db

Revision ID: 1273c3a2c68d
Revises: 
Create Date: 2026-07-16 17:21:00.516818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1273c3a2c68d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aumento_costos',
    sa.Column('id_aumento_costo', sa.Integer(), nullable=False),
    sa.Column('porcentaje_aumento', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('nombre_temporada', sa.String(length=100), nullable=True),
    sa.Column('activado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_aumento_costo'),
    sa.UniqueConstraint('nombre_temporada')
    )
    op.create_index(op.f('ix_aumento_costos_id_aumento_costo'), 'aumento_costos', ['id_aumento_costo'], unique=False)
    op.create_table('descuento',
    sa.Column('id_descuento', sa.Integer(), nullable=False),
    sa.Column('porcentaje_descuento', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cant_dia_hospedado', sa.Integer(), nullable=True),
    sa.Column('activado', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id_descuento')
    )
    op.create_index(op.f('ix_descuento_id_descuento'), 'descuento', ['id_descuento'], unique=False)
    op.create_table('hotel',
    sa.Column('id_hotel', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('niveles_edificios', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_hotel'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_hotel_id_hotel'), 'hotel', ['id_hotel'], unique=False)
    op.create_table('huesped',
    sa.Column('id_huesped', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_huesped'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('documento')
    )
    op.create_index(op.f('ix_huesped_id_huesped'), 'huesped', ['id_huesped'], unique=False)
    op.create_table('servicio',
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_servicio'),
    sa.UniqueConstraint('tipo_servicio')
    )
    op.create_index(op.f('ix_servicio_id_servicio'), 'servicio', ['id_servicio'], unique=False)
    op.create_table('tipo_comodidad',
    sa.Column('id_tipo_comodidad', sa.Integer(), nullable=False),
    sa.Column('tipo_comodidad', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_comodidad'),
    sa.UniqueConstraint('tipo_comodidad')
    )
    op.create_index(op.f('ix_tipo_comodidad_id_tipo_comodidad'), 'tipo_comodidad', ['id_tipo_comodidad'], unique=False)
    op.create_table('tipo_empleado',
    sa.Column('id_tipo_empleado', sa.Integer(), nullable=False),
    sa.Column('tipo_empleado', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_empleado'),
    sa.UniqueConstraint('tipo_empleado')
    )
    op.create_index(op.f('ix_tipo_empleado_id_tipo_empleado'), 'tipo_empleado', ['id_tipo_empleado'], unique=False)
    op.create_table('tipo_habitacion',
    sa.Column('id_tipo_habitacion', sa.Integer(), nullable=False),
    sa.Column('tipo_habitacion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_habitacion'),
    sa.UniqueConstraint('tipo_habitacion')
    )
    op.create_index(op.f('ix_tipo_habitacion_id_tipo_habitacion'), 'tipo_habitacion', ['id_tipo_habitacion'], unique=False)
    op.create_table('comodidad_tipo_habitacion',
    sa.Column('id_comodidad_habitacion', sa.Integer(), nullable=False),
    sa.Column('id_tipo_habitacion', sa.Integer(), nullable=False),
    sa.Column('id_tipo_comodidad', sa.Integer(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_comodidad'], ['tipo_comodidad.id_tipo_comodidad'], ),
    sa.ForeignKeyConstraint(['id_tipo_habitacion'], ['tipo_habitacion.id_tipo_habitacion'], ),
    sa.PrimaryKeyConstraint('id_comodidad_habitacion')
    )
    op.create_index(op.f('ix_comodidad_tipo_habitacion_id_comodidad_habitacion'), 'comodidad_tipo_habitacion', ['id_comodidad_habitacion'], unique=False)
    op.create_table('empleado',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_tipo_empleado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('dui', sa.String(length=10), nullable=False),
    sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_empleado'], ['tipo_empleado.id_tipo_empleado'], ),
    sa.PrimaryKeyConstraint('id_empleado'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('dui')
    )
    op.create_index(op.f('ix_empleado_id_empleado'), 'empleado', ['id_empleado'], unique=False)
    op.create_table('habitacion',
    sa.Column('id_habitacion', sa.Integer(), nullable=False),
    sa.Column('id_hotel', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('numero_habitacion', sa.Integer(), nullable=False),
    sa.Column('id_tipo_habitacion', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_hotel'], ['hotel.id_hotel'], ),
    sa.ForeignKeyConstraint(['id_tipo_habitacion'], ['tipo_habitacion.id_tipo_habitacion'], ),
    sa.PrimaryKeyConstraint('id_habitacion')
    )
    op.create_index(op.f('ix_habitacion_id_habitacion'), 'habitacion', ['id_habitacion'], unique=False)
    op.create_table('reservacion',
    sa.Column('id_reservacion', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_huesped', sa.Integer(), nullable=False),
    sa.Column('cant_huespedes_totales', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id_empleado'], ),
    sa.ForeignKeyConstraint(['id_huesped'], ['huesped.id_huesped'], ),
    sa.PrimaryKeyConstraint('id_reservacion')
    )
    op.create_index(op.f('ix_reservacion_id_reservacion'), 'reservacion', ['id_reservacion'], unique=False)
    op.create_table('detalle_reservacion',
    sa.Column('id_detalle_reservacion', sa.Integer(), nullable=False),
    sa.Column('id_reservacion', sa.Integer(), nullable=False),
    sa.Column('id_habitacion', sa.Integer(), nullable=False),
    sa.Column('cant_huespedes', sa.Integer(), nullable=False),
    sa.Column('fecha_entrada', sa.Date(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_habitacion'], ['habitacion.id_habitacion'], ),
    sa.ForeignKeyConstraint(['id_reservacion'], ['reservacion.id_reservacion'], ),
    sa.PrimaryKeyConstraint('id_detalle_reservacion')
    )
    op.create_index(op.f('ix_detalle_reservacion_id_detalle_reservacion'), 'detalle_reservacion', ['id_detalle_reservacion'], unique=False)
    op.create_table('estadia',
    sa.Column('id_estadia', sa.Integer(), nullable=False),
    sa.Column('id_reservacion', sa.Integer(), nullable=False),
    sa.Column('checkin', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('checkout', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_reservacion'], ['reservacion.id_reservacion'], ),
    sa.PrimaryKeyConstraint('id_estadia')
    )
    op.create_index(op.f('ix_estadia_id_estadia'), 'estadia', ['id_estadia'], unique=False)
    op.create_table('consumo_servicio',
    sa.Column('id_consumo_servicio', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('id_habitacion', sa.Integer(), nullable=False),
    sa.Column('id_estadia', sa.Integer(), nullable=False),
    sa.Column('hora_consumo', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_estadia'], ['estadia.id_estadia'], ),
    sa.ForeignKeyConstraint(['id_habitacion'], ['habitacion.id_habitacion'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ),
    sa.PrimaryKeyConstraint('id_consumo_servicio')
    )
    op.create_index(op.f('ix_consumo_servicio_id_consumo_servicio'), 'consumo_servicio', ['id_consumo_servicio'], unique=False)
    op.create_table('factura',
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_huesped', sa.Integer(), nullable=False),
    sa.Column('id_estadia', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('total_a_pagar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id_empleado'], ),
    sa.ForeignKeyConstraint(['id_estadia'], ['estadia.id_estadia'], ),
    sa.ForeignKeyConstraint(['id_huesped'], ['huesped.id_huesped'], ),
    sa.PrimaryKeyConstraint('id_factura')
    )
    op.create_index(op.f('ix_factura_id_factura'), 'factura', ['id_factura'], unique=False)
    op.create_table('resenia',
    sa.Column('id_resenia', sa.Integer(), nullable=False),
    sa.Column('id_estadia', sa.Integer(), nullable=False),
    sa.Column('id_huesped', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_estadia'], ['estadia.id_estadia'], ),
    sa.ForeignKeyConstraint(['id_huesped'], ['huesped.id_huesped'], ),
    sa.PrimaryKeyConstraint('id_resenia')
    )
    op.create_index(op.f('ix_resenia_id_resenia'), 'resenia', ['id_resenia'], unique=False)
    op.create_table('detalle_factura',
    sa.Column('id_detalle_factura', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=True),
    sa.Column('id_habitacion', sa.Integer(), nullable=True),
    sa.Column('id_descuento', sa.Integer(), nullable=True),
    sa.Column('id_aumento_costo', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_descuento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_aumento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_aumento_costo'], ['aumento_costos.id_aumento_costo'], ),
    sa.ForeignKeyConstraint(['id_descuento'], ['descuento.id_descuento'], ),
    sa.ForeignKeyConstraint(['id_factura'], ['factura.id_factura'], ),
    sa.ForeignKeyConstraint(['id_habitacion'], ['habitacion.id_habitacion'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ),
    sa.PrimaryKeyConstraint('id_detalle_factura')
    )
    op.create_index(op.f('ix_detalle_factura_id_detalle_factura'), 'detalle_factura', ['id_detalle_factura'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_factura_id_detalle_factura'), table_name='detalle_factura')
    op.drop_table('detalle_factura')
    op.drop_index(op.f('ix_resenia_id_resenia'), table_name='resenia')
    op.drop_table('resenia')
    op.drop_index(op.f('ix_factura_id_factura'), table_name='factura')
    op.drop_table('factura')
    op.drop_index(op.f('ix_consumo_servicio_id_consumo_servicio'), table_name='consumo_servicio')
    op.drop_table('consumo_servicio')
    op.drop_index(op.f('ix_estadia_id_estadia'), table_name='estadia')
    op.drop_table('estadia')
    op.drop_index(op.f('ix_detalle_reservacion_id_detalle_reservacion'), table_name='detalle_reservacion')
    op.drop_table('detalle_reservacion')
    op.drop_index(op.f('ix_reservacion_id_reservacion'), table_name='reservacion')
    op.drop_table('reservacion')
    op.drop_index(op.f('ix_habitacion_id_habitacion'), table_name='habitacion')
    op.drop_table('habitacion')
    op.drop_index(op.f('ix_empleado_id_empleado'), table_name='empleado')
    op.drop_table('empleado')
    op.drop_index(op.f('ix_comodidad_tipo_habitacion_id_comodidad_habitacion'), table_name='comodidad_tipo_habitacion')
    op.drop_table('comodidad_tipo_habitacion')
    op.drop_index(op.f('ix_tipo_habitacion_id_tipo_habitacion'), table_name='tipo_habitacion')
    op.drop_table('tipo_habitacion')
    op.drop_index(op.f('ix_tipo_empleado_id_tipo_empleado'), table_name='tipo_empleado')
    op.drop_table('tipo_empleado')
    op.drop_index(op.f('ix_tipo_comodidad_id_tipo_comodidad'), table_name='tipo_comodidad')
    op.drop_table('tipo_comodidad')
    op.drop_index(op.f('ix_servicio_id_servicio'), table_name='servicio')
    op.drop_table('servicio')
    op.drop_index(op.f('ix_huesped_id_huesped'), table_name='huesped')
    op.drop_table('huesped')
    op.drop_index(op.f('ix_hotel_id_hotel'), table_name='hotel')
    op.drop_table('hotel')
    op.drop_index(op.f('ix_descuento_id_descuento'), table_name='descuento')
    op.drop_table('descuento')
    op.drop_index(op.f('ix_aumento_costos_id_aumento_costo'), table_name='aumento_costos')
    op.drop_table('aumento_costos')
    # ### end Alembic commands ###
